#!/bin/bash
$APPDIR/func -reset_gtk
[ -z "$IMG" ] && IMG="dialog-error"
[ -z "$FRAME" ] && FRAME="Error"

export ok_box="
<window icon-name=\"pmusic\" title=\"Pmusic\" allow-grow=\"false\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <text use-markup=\"true\"><label>\"$TXT2\"</label></text>
  </frame>
  <hbox>
   <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
    <input file icon=\"gtk-ok\"></input>
    <label>$LOC_OK</label>
   </button>
  </hbox>
 </vbox>
</window>"
$GTKDIALOG -p ok_box --center
TXT1=""; TXT2=""; IMG=""; FRAME="" #reset to avoid alien values in next box