#! /bin/bash
$APPDIR/func -reset_gtk

if [ -f $WORKDIR/splash_cancelcode ]; then
	GUI_CANCEL='
	<hbox>
	 <button cancel>
	  <action>'"$(<$WORKDIR/splash_cancelcode)"'</action>
	  <action>echo 100 > '$WORKDIR'/splash</action>
	  <action>exit:EXIT</action>
	 </button>
	</hbox>'
	rm $WORKDIR/splash_cancelcode
fi

echo 0 > $WORKDIR/splash
export pmusic_splash='
<window title="Pmusic" icon-name="pmusic" allow-grow="false" skip_taskbar_hint="true">
<vbox>
 <frame>
  <text><label>""</label></text>
  '"<text use-markup=\"true\"><label>\"<b><span color='"'gray30'"' size='"'x-large'"'>Pmusic  </span><span color='"'gray30'"' size='"'large'"'>$VERSION</span></b>\"</label></text>
  <text><input file>$WORKDIR/splashtext</input></text>
 </frame>
 <progressbar>
  <label>Sigmund Berglund,   GPL 2008-2012</label>
  <input>"'while [ "$I" != "100" ]; do I=`cat '"$WORKDIR"'/splash`; echo $I; usleep 500000; done</input>
  <action type="exit">Ready</action>
 </progressbar>
 '$GUI_CANCEL'
</vbox></window>'

$GTKDIALOG -p pmusic_splash --center


