#!/bin/bash
#Firewall Control
#Rob Lane (tasmod) 2009-2011 GPL

cd $HOME
export firewall="
<window title=\"Firewall on/off\">
 <vbox>
   <frame Only use On/Off if firewall already installed with wizard>
   <hbox>
   <button>
   <label>Firewall On</label>
   <input file icon=\"gtk-apply\"></input>
   <action>/usr/local/firewallgtk/firewallfunc firewallstart</action>
   <action>exit:gtkdialog</action>
   </button>
   <button>
   <label>Firewall Off</label>
   <input file icon=\"gtk-cancel\"></input>
   <action>/usr/local/firewallgtk/firewallfunc firewallstop</action>
   <action>exit:gtkdialog</action>
   </button>
   <button>
   <label>Firewall Remove</label>
   <input file icon=\"gtk-cancel\"></input>
   <action>/etc/rc.d/rc.firewall stop</action>
   <action>/usr/local/firewallgtk/firewallfunc firewallkill</action>
   <action>exit:gtkdialog</action> 
   </button>
   </hbox>
   </frame>
   <hbox>
   <button>
   <input file icon=\"gtk-info\"></input>
   <label>    Exit     </label>
   </button>
   </hbox>
   </vbox>
</window>"

#execute gtkdialog
gtkdialog3 -c -p  firewall

