# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.enablesound", false);
user_pref("addressbook.throbber.url", "file:///root/geeps/help.html");
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1351868886);
user_pref("app.update.lastUpdateTime.background-update-timer", 1270208171);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1351869081);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1351868886);
user_pref("app.update.silent", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 4096);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.chrome.toolbar_style", 0);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.dir", "/root/my-documents");
user_pref("browser.download.lastDir", "/root/my-documents");
user_pref("browser.enable_automatic_image_resizing", true);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.history.last_page_visited", "file:///root/geeps/help.html");
user_pref("browser.open.dir", "/usr/share/doc");
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.search.defaultengine", "engine:///usr/lib/seamonkey/searchplugins/google.src");
user_pref("browser.startup.homepage", "file:///usr/share/doc/home.htm");
user_pref("browser.startup.homepage_override.mstone", "rv:12.0");
user_pref("browser.tabs.autoHide", false);
user_pref("browser.tabs.forceHide", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.throbber.url", "file:///root/geeps/help.html");
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.disable_open_during_load", false);
user_pref("editor.prettyprint", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "inspector@mozilla.org:2.0.10,{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}:0.9.88.2,{f13b157f-b174-47e7-a34d-4815ddfdfeb8}:0.9.89,{972ce4c6-7e08-4474-a285-3208198ce6fd}:2.9.1");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/seamonkey/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"mtime\":1350584575000}}},{\"name\":\"app-profile\",\"addons\":{\"{f13b157f-b174-47e7-a34d-4815ddfdfeb8}\":{\"descriptor\":\"/root/.mozilla/seamonkey/dud83p2f.default/extensions/{f13b157f-b174-47e7-a34d-4815ddfdfeb8}.xpi\",\"mtime\":1351868765000},\"{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}\":{\"descriptor\":\"/root/.mozilla/seamonkey/dud83p2f.default/extensions/{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}.xpi\",\"mtime\":1351868765000},\"inspector@mozilla.org\":{\"descriptor\":\"/root/.mozilla/seamonkey/dud83p2f.default/extensions/inspector@mozilla.org.xpi\",\"mtime\":1351868765000}}}]");
user_pref("extensions.installedDistroAddon.inspector@mozilla.org", true);
user_pref("extensions.installedDistroAddon.{59c81df5-4b7a-477b-912d-4e0fdf64e5f2}", true);
user_pref("extensions.installedDistroAddon.{f13b157f-b174-47e7-a34d-4815ddfdfeb8}", true);
user_pref("extensions.lastAppVersion", "2.9.1");
user_pref("extensions.lastPlatformVersion", "12.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.venkman.lastErrorMode", "ignore");
user_pref("extensions.venkman.lastThrowMode", "ignore");
user_pref("extensions.venkman.layoutState.default", "x-vloc:/mainwindow/initial-container?target=container&id=outer&type=horizontal; x-vloc:/mainwindow/outer?target=container&id=gutter&width=231&before=vright&type=vertical; x-vloc:/mainwindow/gutter?target=container&id=top-tab&height=177&before=mid-tab&type=tab; x-vloc:/mainwindow/top-tab?target=view&id=scripts&height=177&before=windows; x-vloc:/mainwindow/top-tab?target=view&id=windows; x-vloc:/mainwindow/gutter?target=container&id=mid-tab&height=121&before=bot-tab&type=tab; x-vloc:/mainwindow/mid-tab?target=view&id=locals&before=watches; x-vloc:/mainwindow/mid-tab?target=view&id=watches; x-vloc:/mainwindow/gutter?target=container&id=bot-tab&height=100&type=tab; x-vloc:/mainwindow/bot-tab?target=view&id=breaks&height=100&before=stack; x-vloc:/mainwindow/bot-tab?target=view&id=stack&height=75; x-vloc:/mainwindow/outer?target=container&id=vright&width=560&type=vertical; x-vloc:/mainwindow/vright?target=view&id=source2&before=session; x-vloc:/mainwindow/vright?target=view&id=session&width=677");
user_pref("extensions.venkman.prettyprint", true);
user_pref("extensions.venkman.startupCount", 1);
user_pref("font.default.x-western", "sans-serif");
user_pref("font.minimum-size.x-western", 12);
user_pref("font.name.cursive.x-western", "serif");
user_pref("font.name.fantasy.x-western", "serif");
user_pref("font.name.sans-serif.x-western", "DejaVu Sans");
user_pref("font.size.fixed.x-western", 14);
user_pref("font.size.variable.x-western", 14);
user_pref("general.open_location.last_url", "about:config");
user_pref("idle.lastDailyNotification", 1277790763);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("ldap_2.servers.default.filename", "default.mab");
user_pref("ldap_2.servers.default.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.default.uri", "moz-abldapdirectory://default.mab");
user_pref("ldap_2.servers.history.replication.lastChangeNumber", 0);
user_pref("ldap_2.servers.pab.replication.lastChangeNumber", 0);
user_pref("mail.biff.play_sound", false);
user_pref("mail.forward_message_mode", 2);
user_pref("mail.spellcheck.inline", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 6476);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("security.enable_java", false);
user_pref("security.password_lifetime", 0);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
