#!/bin/bash
export inputbox="
<window title=\"Pfind\" icon-name=\"gtk-find\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <entry activates-default=\"true\">
    <variable>INPUT</variable>
    <input>echo \"$DEFAULT\"</input>
   </entry>
  </frame>
  <hbox>
   <button>
    <input file icon=\"gtk-cancel\">
    </input><label>$LOC_CANCEL</label>
    <action type=\"exit\">cancel</action>
   </button>
   <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
    <input file icon=\"gtk-apply\"></input>
    <label>$LOC_OK</label>
    <action type=\"exit\">ok</action>
   </button>
  </hbox>
 </vbox>
</window>"
I=$IFS; IFS=""
for STATEMENTS in  $(gtkdialog3 --program=inputbox --class=jwm-ontop --center); do
	eval $STATEMENTS
done
IFS=$I
TXT1=""; DEFAULT=""; FRAME=""; IMG="" #reset to avoid alien text in next box