#!/bin/sh
#usb modem
#Barry Kauler, LGPL 2007

#if a modem found, quit...
[ -h /dev/modem ] && exit

[ ! $1 ] && exit
[ "$1" != "start" ] && exit

#Wait for firmware and driver to load.
/sbin/pup_event_backend_modprobe_protect --modcheck=cdc_acm || exit #v432

#v433 Let high-speed modems to be detected by hso init script.
[ "`grep -l -s 'Modem' /sys/class/tty/ttyHS?*/hsotype`" != "" ] && exit

#Select interrupt-type device - first one or one identified in log as modem.
INTERRUPTLIST="`grep -H -s 'Interrupt' /sys/bus/usb/devices/*-*:*.*/ep_??/type | cut -f 1-6 -d /`"
DEVLISTACM="`ls -1 -d /sys/bus/usb/devices/*-*:*.*/tty/tty????* 2>/dev/null | sed 's/ /\n/g' | grep -F "$INTERRUPTLIST" | cut -f 8 -d / | sed 's/\(tty...\)\([0-9]$\)/\10\2/' | sort | sed 's/\(tty...\)\(0\)/\1/'`"

#echo -e "Script Cdcacm: DEVLIST1:\n`grep -l -s -H 'Interrupt' /sys/bus/usb/devices/*-*:*.*/ep_??/type`" >> /tmp/udevtrace-modem.log  #DEBUG
#echo -e "Script Cdcacm - INTERRUPTLIST:\n$INTERRUPTLIST\nDEVLISTACM:\n$DEVLISTACM" >> /tmp/udevtrace-modem.log  #DEBUG

DEVMLIST="`grep -s ': USB ACM device$' /var/log/messages | grep -o 'ttyACM[0-9][0-9]*' | sort -u`"
if [ "$DEVLISTACM" != "" ] && [ "$DEVMLIST" != "" ];then
 MODEM="`echo "$DEVLISTACM" | grep -F "$DEVMLIST" | head -n 1`"
else
 MODEM="`echo "$DEVMLIST" | head -n 1`"
fi
echo "Script Cdcacm - MODEM: '$MODEM'  DEVLISTACM: '$DEVLISTACM'  DEVMLIST: '$DEVMLIST'" | tr '\n' ' ' | sed 's/ $/\n/' >> /tmp/udevtrace-modem.log  #debug
[ "$MODEM" = "" ] && exit

[ ! -e /dev/$MODEM ] \
 && [ -e /dev/input/$MODEM ] \
 && ln -snf input/$MODEM /dev/$MODEM  #device name for pupdial
ln -snf $MODEM /dev/modem #v433 end

#the module doesn't seem to support any country setting, so...
if [ -f /etc/countryinfo ];then
 SPATTERN="s/^MODEM_COUNTRY_STRING.*/MODEM_COUNTRY_STRING=''/"
 sed -i -e "$SPATTERN" /etc/countryinfo
fi
#.../usr/sbin/gen_modem_init_string reads this variable.

###END###
