#!/bin/bash
#Pprocess - process manager
#Copyright 2007,2008,2009,2010,2011
#Sigmund Berglund

#------------------------------
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2.

#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. <http://www.gnu.org/licenses/>.
#------------------------------

VERSION=2.2.4
#define paths
PROGPATH="`dirname $0`" #Pprocess directory
[ "$PROGPATH" = "." ] && PROGPATH="`pwd`"
export PROGPATH=$PROGPATH

#parameters
while [ $# != 0 ]; do
	I=1
	while [ $I -le `echo $# | wc -c` ]; do #check -xft
		if [ `echo $1 | grep s` ]; then SHUTDOWN=true; fi
		if [ `echo $1 | grep h` ]; then
			echo 'Options
  -s          Show Shutdown/Reboot button
  -h          show this help message.'
  			exit
		fi
		shift
		I=$[$I+1]
	done
done

#set language
TMP="`ls -1 $PROGPATH/locals/ | grep ${LANG%.*}`"
. $PROGPATH/locals/en_US:english #always run to fill gaps in translation
#fallback to macrolanguage if available (ISO 639-1 two letter code: en, es, fr, etc.)
[ -z $TMP ] && TMP="`ls -1 $APPDIR/locals/ | grep ${LANG%_*}:`"
[ "$TMP" != "en_US:english" ] && . $PROGPATH/locals/$TMP 2> /dev/null

#use monofont in <tree>
echo 'style "specialmono"
{
  font_name="Mono 12"
}
widget "*mono" style "specialmono"
class "GtkTree*" style "specialmono"' > /tmp/gtkrc_mono

export GTK2_RC_FILES=/tmp/gtkrc_mono:/root/.gtkrc-2.0 
#---

echo -n > /tmp/pprocess-filter

$PROGPATH/func -filter

S='
<window title="Pprocess '$VERSION' - '$LOC100'" icon-name="gtk-execute" default_height="450" default_width="700">
<hbox>
 <tree headers_visible="false" rules_hint="true" hover-selection="true">
  <label>hei</label>
  <variable>LIST</variable>
  <input>cat /tmp/pprocess-ps</input>
  <action signal="button-press-event">. '$PROGPATH'/func -action</action>
  <action signal="button-press-event">'$PROGPATH'/func -filter</action>
  <action signal="button-press-event">refresh:LIST</action>
 </tree>
 <notebook labels="'$LOC102'|'$LOC103'">
  <frame>
   <vbox tooltip-text="'$LOC200'">
     <entry activates-default="true">
      <variable>FILTER_STRING</variable>
      <default>'$LOC_SEARCHTEXT'</default>
      <width>100</width><height>25</height>
      <action signal="key-release-event">'$PROGPATH'/func -set_filter</action>
     </entry>
    <hbox>
     <button relief="2" can-default="true" has-default="true" use-stock="true" height-request="1" width-request="1">
      <action>'$PROGPATH'/func -filter</action>
      <action>refresh:LIST</action>
     </button>
    </hbox>
##    <progressbar height-request="2">
##     <input>while [ A ]; do $PROGPATH/func -filter; echo; echo 100; sleep 4; done</input>
##     <action>refresh:LIST</action>
##    </progressbar>
    <timer visible="false" interval="4">
     <action>'$PROGPATH'/func -filter</action>
     <action>refresh:LIST</action>
    </timer>
   </vbox>
   <tree tooltip-text="'$LOC201'" headers_visible="false">
    <label>a</label>
    <variable>ACTION</variable>
    <height>100</height><width>270></width>
    <item stock="gtk-cancel">'$LOC101'</item>
    <item stock="gtk-nothing">""</item> 
    <item stock="gtk-go-up">'$LOC104' - '$LOC105'</item> 
    <item stock="gtk-remove">'$LOC104' - '$LOC106'</item> 
    <item stock="gtk-go-down">'$LOC104' - '$LOC107'</item> 
    <item stock="gtk-nothing">""</item> 
    <item stock="gtk-nothing">'$LOC111' 1 - Hangup</item> 
    <item stock="gtk-nothing">'$LOC111' 2 - Interrupt</item> 
    <item stock="gtk-nothing">'$LOC111' 3 - Quit</item> 
    <item stock="gtk-nothing">'$LOC111' 9 - Kill</item> 
    <item stock="gtk-nothing">'$LOC111' 14 - Alarm</item> 
    <item stock="gtk-nothing">'$LOC111' 15 - Terminate</item> 
    <item stock="gtk-nothing">'$LOC111' 18 - Continue</item> 
    <item stock="gtk-nothing">'$LOC111' 19 - Stop</item>
   </tree>'
  [ "$SHUTDOWN" = "true" ] && S=$S'
  <vbox>
  <hbox homogeneous="true"><hbox>
   <pixmap icon_size="5"><input file stock="gtk-refresh"></input></pixmap>
   <button width-request="180">
    <label>" '$LOC119' "</label>
    <action>reboot</action>
   </button>
   <pixmap icon_size="5"><input file stock="gtk-refresh"></input></pixmap>
  </hbox></hbox>
  <hbox homogeneous="true"><hbox>
   <pixmap icon_size="5"><input file stock="gtk-stop"></input></pixmap>
   <button width-request="180">
    <label>" '$LOC118' "</label>
    <action>wmpoweroff</action>
   </button>
   <pixmap icon_size="5"><input file stock="gtk-stop"></input></pixmap>
  </hbox></hbox>
  </vbox>'
   S=$S'</frame>
  <frame>
   <text><label>'$LOC120'</label></text>
   <text><label>""</label></text>
   <tree rules_hint="true" headers_visible="false" exported_column="1">
    <variable>LOG_FILE</variable>
    <label>a|b</label>
    <item>'$LOC112'|top</item>
    <item>'$LOC113'|/var/log/messages</item>
    <item>'$LOC114'|/var/log/Xorg.0.log</item>
    <item>'$LOC115'|/tmp/bootkernel.log</item>
    <item>'$LOC116'|/tmp/bootsysinit.log</item>
    <action>. '$PROGPATH'/func -logfile</action>
   </tree>
   </frame>  
  </notebook>
</hbox>
</window>'
export PPROCESS="`echo "$S" | sed 's/##.*//'`" #I use double hash (##) for comments. --> as #FF0000
#echo "$PPROCESS" > /root/gtk

gtkdialog3 -p PPROCESS

