#!/bin/sh
#(c) Copyright Barry Kauler 2010, bkhome.org
#Lesser GPL license v2 (/usr/share/doc/legal/lgpl-2.1.txt
#note, 3builddistro (in Woof) renames rootfs-skeleton/sbin/initNEW to init.
#perform a f.s. check if file /fsckme.flg exits, otherwise normal startup.
#/etc/rc.d/rc.sysinit creates /fsckme.flg at bootup, rc.shutdown deletes it.
#this script is /sbin/init in the main Puppy f.s., which is the very first to run.
#in the case of not a full hd install, this script just passes execution to busybox init.
#100911 fsckme.err filename changed to fsckme.flg. see also init (initramfs), rc.sysinit, rc.shutdown.
#101020 no longer have /etc/modprobe.conf.
#120408 support minit

INITEXE='/bin/busybox init'
[ -f /sbin/minit ] && INITEXE='/sbin/minit'

[ -d /initrd ] && exec ${INITEXE} #not a full hd install.
[ ! -e /fsckme.flg ] && exec ${INITEXE} #no error.

PATH='/bin:/sbin'
export LANG=C

#only come here if full hd install, and previous improper shutdown.
PDEV1="`cat /fsckme.flg | cut -f 1 -d ','`" #file format: sda1,ext3,
DEV1FS="`cat /fsckme.flg | cut -f 2 -d ','`"
case $DEV1FS in
 ext2|ext3|ext4)
  echo -e "\\033[1;31m"  >/dev/console #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
  echo "Performing filesystem check of '${PDEV1}' after improper shutdown" > /dev/console
  echo -n "NOTE: no progress indication, may take awhile, please wait patiently..."
  echo -e "\\033[0;39m" >/dev/console
  echo  >/dev/console
  busybox mount -t proc none /proc
  busybox mount -o remount,rw /
  rm -f /fsckme.flg
  #creat a ramdisk... 
  #note, Puppy kernels are compiled with 13MB ramdisk, so need to be careful not to fill it up...
  echo 'Creating a ramdisk and populating with a Linux environment...'  >/dev/console
  mkfs.ext2 -q -m 0 /dev/ram0
  mkdir -p /mnt/ram0
  busybox mount -t ext2 /dev/ram0 /mnt/ram0
  #populate the ramdisk...
  mkdir -p /mnt/ram0/old_root
  mkdir /mnt/ram0/bin
  for ONEBIN in "[" "[[" ash autologinroot basename busybox cat chmod chown clear cp cut date dc dd df dirname dmesg du ed expr false find free grep head kill ln login ls lsmod mkdir mknod more mv nice ntfs-3g pidof pwd readlink rev rm rmdir sed sleep sort stat su sync tail tar touch tr true uname usleep waitmax wc which xargs
  do
   if [ -e /bin/$ONEBIN ];then
    cp -a /bin/$ONEBIN /mnt/ram0/bin/
   else
    ln -s busybox /mnt/ram0/bin/$ONEBIN
   fi
  done
  ln -snf busybox /mnt/ram0/bin/ps
  ln -snf busybox /mnt/ram0/bin/rdev
  ln -snf busybox /mnt/ram0/bin/sh
  ln -snf busybox /mnt/ram0/bin/mount
  ln -snf busybox /mnt/ram0/bin/umount
  mkdir /mnt/ram0/sbin
  for ONEBIN in depmod dumpe2fs e2fsck elspci fdisk freeramdisk fsck.ext2 fsck.ext3 fsck.ext4 getty guess_fstype halt hdparm hotplug2stdout hotplug2stdout_notimeout hwclock ifconfig ifplugstatus insmod klogd ldconfig loadkmap losetup lsmod mount.ntfs-3g pivot_root probedisk probedisk2 probepart swapon
  do
   if [ -e /sbin/$ONEBIN ];then
    cp -a /sbin/$ONEBIN /mnt/ram0/sbin/
   else
    ln -s ../bin/busybox /mnt/ram0/sbin/$ONEBIN
   fi
  done
  ln -snf ../bin/busybox /sbin/chroot          #must match
  ln -snf ../bin/busybox /mnt/ram0/sbin/chroot #must match
  ln -snf ../bin/busybox /mnt/ram0/sbin/init
  ln -snf ../bin/busybox /mnt/ram0/sbin/poweroff
  ln -snf ../bin/busybox /mnt/ram0/sbin/reboot
  mkdir /mnt/ram0/etc
  #101020 no longer have /etc/modprobe.conf...
  for ONEFILE in codepage DISTRO_SPECS eventmanager fdprm floppy fontmap group gshadow host.conf hostname hosts hosts.allow hosts.deny inittab inoutrc issue keymap localtime mailcap mime.types mke2fs.conf modules.conf mtab networks nscd.conf nsswitch.conf passwd printcap protocols services shadow
  do
   cp -a /etc/$ONEFILE /mnt/ram0/etc/ 2>/dev/null
  done
  cp -a /etc/modprobe.d /mnt/ram0/etc/ 2>/dev/null #101020
  echo '/lib' > /mnt/ram0/etc/ld.so.conf
  echo 'export PATH="/bin:/sbin"
export LD_LIBRARY_PATH="/lib"
ulimit -c 0
umask 022
export USER=root
export LOGNAME=root
export TERM=linux' > /mnt/ram0/etc/profile
  LOCALTIME="/usr/share`readlink /etc/localtime | sed 's%^.*/zoneinfo%/zoneinfo%'`"
  LOCALTDIR="`dirname $LOCALTIME`"
  mkdir -p /mnt/ram0/$LOCALTDIR
  cp -a $LOCALTIME /mnt/ram0/$LOCALTDIR/
  mkdir /mnt/ram0/etc/rc.d
  echo "#!/bin/sh
echo 'Now running in ramdisk, performing filesystem check of ${PDEV1}...'
/bin/busybox mount -t proc none /proc
/sbin/hwclock --hctosys --localtime
/bin/busybox umount /old_root
[ $? -ne 0 ] && echo 'Not so good, was unable to unmount ${PDEV1}. Continuing with f.s. check...'
/sbin/e2fsck -p -f /dev/${PDEV1}
/bin/busybox sync
echo 'Filesystem check completed!'
echo 'The computer now has to be restarted.'
echo 'Computer will reboot in 4 minutes, else press ENTER for immediate reboot.'
echo
echo -n 'Press ENTER key to reboot:'
read -t 240 abcdef
/bin/busybox umount /proc
/bin/busybox reboot" > /mnt/ram0/etc/rc.d/rc.sysinit
  chmod 755 /mnt/ram0/etc/rc.d/rc.sysinit
  cp -a /dev /mnt/ram0/
  mkdir /mnt/ram0/lib
  cp -a /lib/lib*.so* /mnt/ram0/lib/
  cp -a /lib/ld*.so* /mnt/ram0/lib/
  cp -a /lib/e2initrd_helper /mnt/ram0/lib/ 2>/dev/null #dunno what this is.
  mkdir /mnt/ram0/tmp
  mkdir -p /mnt/ram0/var/run
  mkdir /mnt/ram0/proc
  mkdir -p /mnt/ram0/usr/share
  cp -a /usr/share/terminfo /mnt/ram0/usr/share/
  #cleanup files...
  rm -f /var/log/X*
  rm -rf /tmp/*
  rm -f /var/lock/LCK*
  rm -f /var/run/*.pid
  rm -rf /root/tmp 2>/dev/null
  rm -rf /root/.thumbnails/* 2>/dev/null
  rm -f `find /var -mount -type s | tr '\n' ' '` #remove sockets.
  rm -f `find /var -mount -type p | tr '\n' ' '` #remove pipes.
  sync
  #pivot_root to the ramdisk...
  echo 'Performing a pivot_root to the ramdisk...'  >/dev/console
  busybox mount -o remount,ro /
  busybox umount /proc
  cd /mnt/ram0
  pivot_root . old_root
  exec chroot . sh -c "exec /bin/busybox init" <dev/console >dev/console 2>&1
  #...the ramdisk is setup so that /etc/rc.d/rc.sysinit will run, which does the f.s. check.
 ;;
 *)
  echo -e "\\033[1;31m"  >/dev/console #34=blue, 33=yellow, 32=green, 31=red, 35=purple, 36=aquablue, 38=black.
  echo -n "Previous improper shutdown, sorry can only do f.s. check of ext2/3/4. Rebooting..." > /dev/console
  echo -e "\\033[0;39m" >/dev/console
  sleep 5
  exec ${INITEXE}
 ;;
esac

###END###
