#!/bin/bash
#(c) copyright 2007 Barry Kauler
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#launched from ~/.xinitrc, so X is running.
#note, see also /usr/sbin/savepuppyd, launched from /etc/rc.d/rc.local0.
#v3.91 BK oct,nov 2007, upated for Dingo.
#v3.94 BK 15 dec 2007, updated.
#v4.01 BK 19may2008: don't think loading usb-storage reqd here anymore.
#v4.01 BK 19may2008: note the new pup_eventd also launched from .xinitrc.
#w007 path fix for Xorg.
#w481 warning if modules cannot be loaded.
#100404 fix load applets for fbpanel. 100413 think needs some 'sleep 0.1'
#100504 background color for retrovol.
#100511 for ram-challenged pc, better to display welcome1stboot.png.
#100513 jwm tray now uses freememapplet_tray and blinky_tray. NOTE: future, move these to /root/Startup.
#100517 freememapplet_tray moved to /root/Startup.
#100522 'surfer' is a simple viewer (uses libgtkhtml).
#100608 if yaf-splash symlink to gtkdialog-splash, use '-fontsize large' parameter.
#100821 01micko: fixes for background color in tray apps, also launch first-run.sh.
#100917 have removed -font parameter from yaf-splash (see /usr/share/doc/yaf-splash-new.htm).
#101004 jemimah has disabled tray applet in retrovol, now using obmixer_tray.
#101007 sound alias modprobe info may have moved.
#101009 problem as tray applets only got launched after welcome msg exited.
#101017 Alsa modprobe file now /etc/modprobe.d/alsa.conf.
#101019 welcome1stboot is now a gtkdialog app...
#101112 alsa info in two different places.
#101120, 101121 fix sound test, rewritten /sbin/pup_event_backend_modprobe.
#101210 pup_event_alsa_cnt* are now in /tmp/pup_event_backend.
#110113 test /dev/mixer for sound ready, see /etc/init.d/10alsa.
#20110328 if mouse not working, popup dialog.
#110412 welcome1stboot now written in BaCon, in /usr/sbin.
#110516 only popup dlg for mouse not working, if DISTRO_XORG_AUTO='yes' (in /etc/DISTRO_SPECS)
#110807 take out pngoverlay code, doing it in woof 3builddistro.
#110925 fix, improvements, for flash player download.
#111010 create /tmp/delayedrun_finished_flag to flag when this script exited.
#111019 DISTRO_XORG_AUTO==yes and PUPMODE==5, run 'quickcountry'. mouse-checking moved to 'mousecheck'.
#111026 decided not to run 'mousecheck' from here. instead, a button in 'quicksetup'.
#111110 ping 64.233.169.103 address no longer responding. 01micko: use 8.8.8.8
#111112 delay a bit more before flashplayer popup.
#111113 fix for download url for flash player. 111117 fix.
#120110 added sudo line. see also /etc/sudoers -- set delayedrun does not require password, probably a security hole, need to look at it again later.
#120201 rodin.s: internationalized.

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #120110

export TEXTDOMAIN=delayedrun
export OUTPUT_CHARSET=UTF-8
. gettext.sh

#variables created at bootup by 'init' in initramfs...
. /etc/rc.d/PUPSTATE
. /etc/DISTRO_SPECS

BGOPT=""
#100821 start...
WINDOWMANAGER="`cat /etc/windowmanager`"
case $WINDOWMANAGER in
 icewm*) #icewm or icewm-session.
  #micko for icewm, not sure why it's needed but it doesn't work without killing the ice tray. It's mainly so freememapplet_tray, network_tray and retrovol work.
  killall icewmtray
  icewmtray & 2>/dev/null 
  . $HOME/.icewm/theme
  THEMEDIR="/usr/share/icewm/themes"
  . ${THEMEDIR}/${Theme} 2>/dev/null
  NUMCOLOR=`echo $ColorNormalTaskBarApp|grep "rgb:"`
  if [[ $NUMCOLOR = "" ]];then BG=""
  else PRE_BG=`echo $ColorNormalTaskBarApp|cut -d ':' -f2|sed 's%/%%g'`
   BG="#${PRE_BG}"   #this is more generic and works with many themes.
  fi
  if [[ $Theme = "GoldenSand/default.theme" ]];then 
   BG="#C6AD73" #this is particular to 5.1, it can be removed for cleanliness
  fi
  if [ "$BG" = "" ];then 
   BGOPT=""
  else 
   BGOPT="-bg ${BG}"
  fi
 ;;
 *) 
  if [ -f /root/.jwm/jwm_colors ];then #100504
   . /root/.jwm/jwm_colors
    BGOPT="-bg ${MENU_BG}"
  fi
 ;;
esac
#10821 end.
export BGOPT #101013 for use in /root/Startup/retrovol_tray

#BGOPT stuff removed 120225

#FONTSIZEPARAM=''
#[ -h /usr/bin/yaf-splash ] && FONTSIZEPARAM='-fontsize large' #100608

KERNVER="`uname -r`" #w481

BAREVIEW="bareview"
[ "`which bareview`" = "" ] && BAREVIEW="defaulthtmlviewer"

sleep 2 #let the dust settle first.

#more BGOPT stuff removed 120225 

#offer to popup a getting-started html page...
#the test for /etc/videomode is for when Xvesa has finished choosing a resolution...
#if [ "`readlink /usr/bin/X`" = "Xorg" -o -e /etc/videomode ];then #w007
 if [ $PUPMODE -eq 5 ];then
  if [ -c /dev/mixer ];then #110113 test for sound ready, see /etc/init.d/10alsa.
    aplay /usr/share/audio/2barks.au &
    #wavplay /usr/share/audio/2barks.wav &
    RETAPLAY=$?
    PIDAPLAY=$!
    sleep 3
    [ $RETAPLAY -eq 0 ] && kill $PIDAPLAY 2> /dev/null
  fi
 fi #comment this fi to restore
  ##if [ "$DISTRO_XORG_AUTO" = "yes" ];then #see /etc/DISTRO_SPECS 111019
   ####detect dead mouse, put up keyboard-operated window after 8 secs... 111026 no
   ###mousecheck &
   ###quick setup window for country and language and X resolution...
   ###QUICKSETUP="quicksetup"
   ###[ "`readlink /usr/bin/X | grep 'Xorg'`" = "" ] && QUICKSETUP="quickcountry" #probably Xvesa, offer country settings only.
   ###echo 'runquery' >> /tmp/delayedrun_quicksetup_count #run 'quicksetup' once only.
   ###[ "`cat /proc/cmdline | grep -i -o 'pfix=[^ ]*' | grep -E 'nox|safe'`" != "" ] && echo 'runquery' >> /tmp/delayedrun_quicksetup_count #the text-mode 1st-start dlgs have already run.
   ###[ `cat /tmp/delayedrun_quicksetup_count | wc -l` -lt 2 ] && ${QUICKSETUP}
  ###fi
  ###welcome1stboot.sh & #110412 now in /usr/sbin #gtkdialog gui for slacko, calls welcome1stboot if no net con 120225
   ####sleep 3 #101009
 ##fi
#fi
#v2.16 popup the BootManager if an extra SFS file added (once only)... #removed 120428
if [ ! $PUPMODE -eq 5 ];then
 if [ -d /initrd ];then #test it isn't full hd installation.
  . /etc/rc.d/BOOTCONFIG
  #if EXTRASFSLIST variable not there, then auto-load of SFS files (meaning, user
  # has probably never run the BootManager)...
  if [ "`grep '^EXTRASFSLIST' /etc/rc.d/BOOTCONFIG`" = "" ];then
   #see /initrd/init which writes these to BOOTCONFIG..
   if [ "$LASTUNIONRECORD" != "" ];then
    if [ "$LASTUNIONRECORD" != "$PREVUNIONRECORD" ];then
     #bootmanager extrasfs quiet
     #we try sfs_load
     sfs_load
    fi
   fi
  fi
 fi
fi

#101121 handle multiple sound cards...
if [ $PUPMODE -eq 5 ];then
 if [ -f /tmp/rc_d_rc_services_alsa_ok ];then #see /etc/rc.d/rc.services
  if [ `find /tmp/pup_event_backend -maxdepth 1 -type f -name 'pup_event_alsa_cnt*' | wc -l` -gt 1 ];then
   #run kirk's Multiple Sound Card Wizard...
   Multiple-Sound-Card-Wizard
  fi
 fi
fi

#v2.16 popup a warning if booting from usb flash...
if [ "$PMEDIA" = "usbflash" ];then
 yaf-splash -close never -fontsize large -bg yellow -timeout 3 -text "$(gettext 'WARNING! Do not unplug USB Flash drive!')" & #101009
fi

#v2.17 suggested by andrei...
if [ -d /root/Startup ];then
 for a in /root/Startup/*
 do
  [ -x "$a" ] && $a &
  sleep 0.2
 done
fi

#101027 install adobe flash player... 110925 fixes, improvements... #120429 let the punters know it's there
#wait for internet connection, do this only until internet connected 1st time...
if [ ! -f /var/local/internetsuccess ];then
 if [ ! -f /usr/lib/mozilla/plugins/libflashplayer.so ];then
  if [ ! -f $HOME/.flashrunflag ];then #create flag so getflash doesn't run if NO answered 120127
   sleep 10 #add for slower hardware 120127
   while [ ! -f $HOME/.flashrunflag ];do #changed condition to break loop 
    #test for valid internet connection... #uncommented for Slacko 111114 to restore if browser is running
    sleep 6 
    ALLPS="`ps`"
    if [ "`echo "$ALLPS" | grep -E 'seamonkey|firefox|opera'`" != "" ];then
    sleep 2
    IFCONFIG="`ifconfig | grep '^[pwe]' | grep -v 'wmaster'`"
     if [ "$IFCONFIG" ];then
     #exec getflash #120428 commented
     Xdialog --title "Flash Player" --icon "/usr/share/doc/flashlogo.gif" --yesno\
      "The Latest Adobe Flash Player is available for download. \nFor older Computers an older version \nis available from Slickpet. \n\nYou can install the latest later from the menu. \n\nWould you like to install the latest Flash Player now?" 0 0
      case $? in
      0)exec getflash ;;
      *)touch $HOME/.flashrunflag ;;
      esac
     fi
    fi
   done
  fi
 fi
fi


touch /tmp/delayedrun_finished_flag #111010
###END###

