#!/bin/bash
#(c) copyright 2007 Barry Kauler
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#launched from ~/.xinitrc, so X is running.
#note, see also /usr/sbin/savepuppyd, launched from /etc/rc.d/rc.local0.
#v3.91 BK oct,nov 2007, upated for Dingo.
#v3.94 BK 15 dec 2007, updated.
#v4.01 BK 19may2008: don't think loading usb-storage reqd here anymore.
#v4.01 BK 19may2008: note the new pup_eventd also launched from .xinitrc.
#w007 path fix for Xorg.
#w481 warning if modules cannot be loaded.
#100404 fix load applets for fbpanel. 100413 think needs some 'sleep 0.1'
#100504 background color for retrovol.
#100511 for ram-challenged pc, better to display welcome1stboot.png.
#100513 jwm tray now uses freememapplet_tray and blinky_tray. NOTE: future, move these to /root/Startup.
#100517 freememapplet_tray moved to /root/Startup.
#100522 'surfer' is a simple viewer (uses libgtkhtml).
#100608 if yaf-splash symlink to gtkdialog-splash, use '-fontsize large' parameter.
#100821 01micko: fixes for background color in tray apps, also launch first-run.sh.
#100917 have removed -font parameter from yaf-splash (see /usr/share/doc/yaf-splash-new.htm).
#101004 jemimah has disabled tray applet in retrovol, now using obmixer_tray.
#101007 sound alias modprobe info may have moved.
#101009 problem as tray applets only got launched after welcome msg exited.
#101017 Alsa modprobe file now /etc/modprobe.d/alsa.conf.
#101019 welcome1stboot is now a gtkdialog app...
#101112 alsa info in two different places.
#101120, 101121 fix sound test, rewritten /sbin/pup_event_backend_modprobe.
#101210 pup_event_alsa_cnt* are now in /tmp/pup_event_backend.
#110113 test /dev/mixer for sound ready, see /etc/init.d/10alsa.
#20110328 if mouse not working, popup dialog.
#110412 welcome1stboot now written in BaCon, in /usr/sbin.
#110516 only popup dlg for mouse not working, if DISTRO_XORG_AUTO='yes' (in /etc/DISTRO_SPECS)
#110807 take out pngoverlay code, doing it in woof 3builddistro.
#110925 fix, improvements, for flash player download.
#111010 create /tmp/delayedrun_finished_flag to flag when this script exited.
#111019 DISTRO_XORG_AUTO==yes and PUPMODE==5, run 'quickcountry'. mouse-checking moved to 'mousecheck'.
#111026 decided not to run 'mousecheck' from here. instead, a button in 'quicksetup'.
#111110 ping 64.233.169.103 address no longer responding. 01micko: use 8.8.8.8
#111112 delay a bit more before flashplayer popup.
#111113 fix for download url for flash player. 111117 fix.
#120110 added sudo line. see also /etc/sudoers -- set delayedrun does not require password, probably a security hole, need to look at it again later.
#120201 rodin.s: internationalized.
# 16mar12,12apr14: shinobar: example for firstrun

[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #120110

export TEXTDOMAIN=delayedrun
export OUTPUT_CHARSET=UTF-8
[ -s gettext.sh ] && . gettext.sh	# shinobar

#variables created at bootup by 'init' in initramfs...
. /etc/rc.d/PUPSTATE
. /etc/DISTRO_SPECS

#28mar2012: everytime comment out DISTRO_XORG_AUTO because it revives every boot
if [ -s /etc/DISTRO_SPECS ]  && grep -q '^[[:space:]]*DISTRO_XORG_AUTO=.*yes' /etc/DISTRO_SPECS; then
  rm -f /tmp/DISTRO_SPECS
  grep -v 'DISTRO_XORG_AUTO=' /etc/DISTRO_SPECS > /tmp/DISTRO_SPECS
  echo "#DISTRO_XORG_AUTO='yes'" >> /tmp/DISTRO_SPECS
  [ -s /tmp/DISTRO_SPECS ]  &&  mv -f /tmp/DISTRO_SPECS /etc/DISTRO_SPECS
fi

#BGOPT stuff removed 120225

sleep 2 #let the dust settle first.

#more BGOPT stuff removed 120225 
# shinobar: bark by the script /root/Startup/firstrun

# shinobar: need not call quicksetup unless another /root/Startup stuff disturb
# QUICKSETUP=quicksetup
# [ "$QUICKSETUP" ] && "$QUICKSETUP"

# shinobar: do not popup the BootManager

#101121 handle multiple sound cards...
if [ $PUPMODE -eq 5 ];then
 if [ -f /tmp/rc_d_rc_services_alsa_ok ];then #see /etc/rc.d/rc.services
  if [ `find /tmp/pup_event_backend -maxdepth 1 -type f -name 'pup_event_alsa_cnt*' | wc -l` -gt 1 ];then
   #run kirk's Multiple Sound Card Wizard...
   Multiple-Sound-Card-Wizard
  fi
 fi
fi

#v2.16 popup a warning if booting from usb flash...
if [ "$PMEDIA" = "usbflash" ];then
 yaf-splash -close never -fontsize large -bg yellow -timeout 3 -text "$(gettext 'WARNING! Do not unplug USB Flash drive!')" & #101009
fi

#v2.17 suggested by andrei...
if [ -d /root/Startup ];then
 for a in /root/Startup/*
 do
  [ -x "$a" ] && $a &
  sleep 0.2
 done
fi

# shinobar: do not offer installing adobe flash player... 110925 fixes, improvements...

touch /tmp/delayedrun_finished_flag #111010
###END###

