#!/bin/sh
#Barry Kauler Oct. 2011
#this is called from Internet Connection Wizard, script ''.
#111028 have copied dlg code inside 'connectwizard' script, then call here with hostname passed param.
#111028 fully internationalised.
#111103 gcmartin: accept '-' char in hostname.
#111103 gcmartin: current hostname is $HOSTNAME, but if rerun this script before restarting X, need to get from /etc/hostname.
#111106 fix passed hostname from connectwizard.
#111117 shinobar: fix.
#120227 can also be called from quicksetup. now have exit #

export TEXTDOMAIN=hostname-set
export OUTPUT_CHARSET=UTF-8

#111103 current hostname is $HOSTNAME, but if rerun this script before restarting X, need to get from here...
[ -f /etc/hostname ] && HOSTNAME="`cat /etc/hostname`"

NEW_HOSTNAME="$HOSTNAME" #111106
[ $1 ] && NEW_HOSTNAME="$1"

GTKDIALOGEXE="gtkdialog"
[ "`which gtkdialog4`" ] && GTKDIALOGEXE="gtkdialog4"

WINTITLE=$(gettext 'Set Hostname')
M_1=$(gettext 'Type your computer name to identify in the network. Alpha-numeric without spaces.')
M_2=$(gettext "Your computer has been assigned a unique name, known as the 'hostname', by which it identifies itself on a network. However, you might wish to change that to a name that is more meaningful to yourself, such as 'johnsmithpc'. The hostname can have letters and numbers, no spaces.")

if [ "$1" = "" ];then #111028 111117
 export HOSTNAME_DIALOG="<window title=\"${WINTITLE}\" window_position=\"1\" icon-name=\"mini-hostname\">
 <vbox>
 
  <text><label>${M_2}</label></text>
 
  <hbox>
   <text><label>$(gettext 'Hostname'):</label></text>
   <entry tooltip-text=\"${M_1}\">
   <input>echo -n \"$NEW_HOSTNAME\"</input><variable>ENTRY_HOSTNAME</variable></entry>
  </hbox>
  
  <hbox>
   <button ok></button>
   <button cancel></button>
  </hbox>

 </vbox>
</window>"

 RETVALS="`${GTKDIALOGEXE} --program=HOSTNAME_DIALOG`"
 eval "$RETVALS"
 [ "$EXIT" != "OK" ] && exit

 NEW_HOSTNAME="`echo -n "$ENTRY_HOSTNAME" | sed -e 's%[^0-9a-zA-Z-]%%g'`" #111103 gcmartin: accept '-' char.
fi

if [ "$NEW_HOSTNAME" != "$HOSTNAME" ];then
 hostname $NEW_HOSTNAME
 echo -n $NEW_HOSTNAME > /etc/hostname
 echo "127.0.0.1 localhost $NEW_HOSTNAME" > /tmp/hostname-set-hosts
 grep -vw 'localhost'  /etc/hosts >> /tmp/hostname-set-hosts
 [ -s /tmp/hostname-set-hosts ] && mv -f /tmp/hostname-set-hosts /etc/hosts
 M_h1=$(gettext 'Set Hostname: done')
 M_h2a=$(gettext 'New hostname')
 M_h2b=$(gettext 'has been set.')
 M_h3=$(gettext 'However, it will not take full effect until after X (the desktop) has been restarted.')
 pupdialog --title "${M_h1}" --msgbox "${M_h2a} '${NEW_HOSTNAME}' ${M_h2b}
${M_h3}" 0 0
 exit 0
else #111028
 M_h4=$(gettext 'Set Hostname')
 M_h5a=$(gettext 'The hostname is:')
 M_h5b=$(gettext 'You have not changed it.')
 pupdialog --title "${M_h4}" --msgbox "${M_h5a} '${NEW_HOSTNAME}'
${M_h5b}" 0 0
 exit 1
fi

###END###
