#!/bin/sh
#Ptiming
#Copyright 2011, 2012
#Sigmund Berglund - Valåmoen, Norway.

#------------------------------
#This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2.

#This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. <http://www.gnu.org/licenses/>.
#------------------------------


save(){
	cd $HOME
	echo "$HOME/pTiming.csv" > $WORKDIR/SAVEFILE
	echo pTiming.csv > $WORKDIR/SAVEFILE_NAME

	export savebox='
	<window title="pTiming - '$LOC502'" icon-name="gtk-no" resizable="false">
	 <vbox>
	  <entry><variable>SAVEFILE</variable><input>cat '$WORKDIR'/SAVEFILE_NAME</input></entry>
	  <chooser>
	   <height>400</height><width>600</width>
	   <variable>CHOOSER</variable>
	   <action>[ -f "$CHOOSER" ] && basename "`echo "$CHOOSER"`" > '$WORKDIR'/SAVEFILE_NAME</action>
	   <action>refresh: SAVEFILE</action>
	  </chooser>
	  <hbox>
	   <button cancel></button>
	   <button can-default="true" has-default="true" use-stock="true"><input file icon="gtk-save"></input><label>'$LOC502'</label><action type="exit">save</action></button>
	  </hbox>
	 </vbox>
	</window>'

	I=$IFS; IFS=""
	for STATEMENTS in  $(gtkdialog4 -p savebox); do
		eval $STATEMENTS
	done
	IFS=$I

	if [ "$EXIT" = "save" ]; then
		CHOOSER="`dirname "$CHOOSER"`" #we want to define the dir we're standing in, not the autoselected one.
		SAVEFILE="`echo "$CHOOSER"/"$SAVEFILE".csv | sed -e "s%\.csv.csv%.csv%g"`" #remove double extension if exist.
		#check if exist
		if [ -f "${SAVEFILE}" ]; then #already exist
			IMG=warning; FRAME=Warning; TXT1="<b>File already exist</b>"; TXT2="Overwrite?"
			. $APPDIR/box_yesno
			[ $EXIT = yes ] && mv $WORKDIR/pTiming.csv "$SAVEFILE"
		else
			mv $WORKDIR/pTiming.csv "$SAVEFILE"
		fi
	fi
}

open(){
	export openbox='
	<window title="pTiming - '$LOC501'" icon-name="gtk-no">
	 <vbox>
	   <chooser>
		<height>400</height><width>600</width>
		<variable>CHOOSER</variable>
	   </chooser>
	  <hbox>
	   <button cancel></button>
	   <button can-default="true" has-default="true" use-stock="true">
	    <input file icon="gtk-open"></input>
	    <label>'$LOC501'</label>
	    <action>tac "$CHOOSER" | sed '"'"'s/","/|/g'"'"' | sed "s/^\"//g" | sed "s/\"$//g" > '$WORKDIR'/startlist</action>
	    <action type="exit">open</action>
	    <action>refresh:STARTLIST</action>
	   </button>
	  </hbox>
	 </vbox>
	</window>'

	I=$IFS; IFS=""
	for STATEMENTS in  $(gtkdialog4 -p openbox); do
		eval $STATEMENTS
	done
	IFS=$I
}

edit(){
	[ ! "$STARTLIST" ] && exit
	#read info from list
	EDIT_NR=`grep "^$STARTLIST|" $WORKDIR/startlist | cut -d'|' -f1`
	NR=$EDIT_NR #check if changed after 'apply'
	EDIT_TIME=`grep "^$STARTLIST|" $WORKDIR/startlist | cut -d'|' -f2`
	EDIT_NAME=`grep "^$STARTLIST|" $WORKDIR/startlist | cut -d'|' -f3`
	EDIT_ORG=`grep "^$STARTLIST|" $WORKDIR/startlist | cut -d'|' -f4`
	EDIT_CLASS=`grep "^$STARTLIST|" $WORKDIR/startlist | cut -d'|' -f5`
	#geometry
	XWININFO=`xwininfo -stats -name $LOC112`
	WIDTH=`echo "$XWININFO" | grep 'Width:' | awk '{print $2}'`
	export X=`echo "$XWININFO" | grep 'Absolute upper-left X' | awk '{print $4}'` #export to use in <progressbar> loop
	export Y=$(((`getcurpos | awk '{print $2}'`)-20))
	#---
	export Competitors_edit='
	<window height-request="50" width-request="'$WIDTH'" skip-taskbar-hint="true" decorated="false">
	 <vbox>
	  <hbox width-request="1">
	   <progressbar width-request="1" height-request="1" >
	    <input>LOOP2=true; while [ $LOOP2 = true ]; do MOUSEX=`getcurpos | awk '"'"'{print $1}'"'"'`; MOUSEY=`getcurpos | awk '"'"'{print $2}'"'"'`; if [ $MOUSEX -lt $X ] || [ $MOUSEX -gt '$(($X+$WIDTH))' ] || [ $MOUSEY -lt $Y ] || [ $MOUSEY -gt '$(($Y+50))' ]; then LOOP2=false; echo; echo 100; fi; sleep 1; done</input>
	    <action>EXIT:exit</action>
	   </progressbar>
	  </hbox>
	  <hbox>
	   <entry name="edit" width-request="35" activates-default="true" tooltip-text="'$LOC310'"><input>echo '$EDIT_NR'</input><variable>EDIT_NR</variable></entry>
	   <entry name="edit" width-request="80" activates-default="true" tooltip-text="'$LOC310'"><input>echo '$EDIT_TIME'</input><variable>EDIT_TIME</variable></entry>
	   <entry name="edit" width-request="130" activates-default="true" tooltip-text="'$LOC310'"><input>echo "'$EDIT_NAME'"</input><variable>EDIT_NAME</variable></entry>
	   <entry name="edit" width-request="115" activates-default="true" tooltip-text="'$LOC310'"><input>echo "'$EDIT_ORG'"</input><variable>EDIT_ORG</variable></entry>
	   <entry name="edit" width-request="85" activates-default="true" tooltip-text="'$LOC310'"><input>echo "'$EDIT_CLASS'"</input><variable>EDIT_CLASS</variable></entry>
	   <text width-request="'$(($WIDTH-565))'"><label>""</label></text>
	   <button visible="false" can-default="true" has-default="true"><action>EXIT:apply</action></button>
	   <vbox homogeneous="true"><button height-request="30" tooltip-text="'$LOC513'"><input file stock="gtk-delete"></input><action>EXIT:delete</action></button></vbox>
	  </hbox>
	 </vbox>
	 <action signal="focus-out-event">EXIT:exit</action>
	</window>'
	gtkdialog4 -p Competitors_edit -G +"$X"+"$Y" > $WORKDIR/returnvalues
	chmod 722 $WORKDIR/returnvalues
	. $WORKDIR/returnvalues
	case $EXIT in
		delete)
			grep -v "^$STARTLIST" $WORKDIR/startlist > $WORKDIR/tmp
			mv -f $WORKDIR/tmp $WORKDIR/startlist
			;;
		apply)
			if [ $EDIT_NR != $NR ] && [ "`grep "^$EDIT_NR" $WORKDIR/startlist`" ]; then 
				TXT1="Nr already exist"; . $APPDIR/box_ok
			else
				HOUR=`echo $EDIT_TIME | cut -d: -f1`
				MIN=`echo $EDIT_TIME | cut -d: -f2`
				SEC=`echo $EDIT_TIME | cut -d: -f3`
				EDIT_SEC=`echo "($HOUR*3600)+($MIN*60)+$SEC" | bc`
				grep -B 10000 "^$STARTLIST" $WORKDIR/startlist | grep -v "^$STARTLIST" > $WORKDIR/tmp
				grep -A 10000 "^$STARTLIST" $WORKDIR/startlist | grep -v "^$STARTLIST" > $WORKDIR/tmp1
				echo "$EDIT_NR|$EDIT_TIME|$EDIT_NAME|$EDIT_ORG|$EDIT_CLASS||$EDIT_SEC" >> $WORKDIR/tmp
				cat $WORKDIR/tmp1 >> $WORKDIR/tmp
				mv -f $WORKDIR/tmp $WORKDIR/startlist
			fi
			;;
	esac
}

generate (){
	cut -d '|' -f5 $WORKDIR/startlist | grep -v "^$" | sort -u > $WORKDIR/classes #find classes
	#build <tree> input
	echo -n > $WORKDIR/class_starttime
	COUNT=0
	while read CLASS; do
		PNR=`grep -c "|$CLASS|" $WORKDIR/startlist`
		SEC=$COUNT
		COUNT=$((($COUNT)+(($PNR+$LATE_REGISTRATION)*$START_INTERVAL))) #total length of starting procedure for given class
		STARTTIME=`printf "%02d:%02d:%02d" $((SEC/3600)) $((SEC%3600/60)) $((SEC%60))`
		echo "$CLASS|$PNR|$STARTTIME||$SEC" >> $WORKDIR/class_starttime
	done < $WORKDIR/classes
	#---
	export generator='
	<window title="'$LOC600'" icon-name="gtk-no" height-request="300">
	 <vbox>
	  <frame>
	   <hbox>
	    <text><label>'$LOC601'</label></text>
	    <hbox><entry width-request="40"><variable>GENERATOR_NR</variable><default>1</default></entry></hbox>
	   </hbox>
	   <hbox>
	    <text><label>'$LOC602'</label></text>
        <hbox><entry width-request="40"><variable>START_INTERVAL</variable><default>'$START_INTERVAL'</default></entry></hbox>
	   </hbox>
	   <tree hover_selection="true" headers-clickable="false">
	    <label>'$LOC125'|'$LOC112'|'$LOC603'|                                                                                  |</label>
	    <variable>CLASS_STARTTIME</variable>
	    <input>cat '$WORKDIR'/class_starttime</input>
		<action signal="button-press-event">generate_edit</action>
		<action signal="button-press-event">refresh:CLASS_STARTTIME</action>
	   </tree>
	  </frame>
	  <hbox>
	   <button cancel></button>
	   <button can-default="true" has-default="true" use-stock="true">
	    <input file icon="gtk-execute"></input>
	    <label>'$LOC604'</label>
	    <action type="exit">generate</action>
	   </button>
	  </hbox>
	 </vbox>
	</window>'

	I=$IFS; IFS=""
	for STATEMENTS in  $(gtkdialog4 -p generator); do
		eval $STATEMENTS
	done
	IFS=$I
	
	if [ $EXIT = generate ]; then
		echo -n > $WORKDIR/startlist_generated
		while read CLASS; do
			#set class starttime
			SEC=`grep "^$CLASS|" $WORKDIR/class_starttime | cut -d'|' -f5`
			#ramdonize Competitors in class
			grep "|$CLASS|" $WORKDIR/startlist | sort -Ru > $WORKDIR/tmp2
			#set new time/nr
			while read P; do
				NAME=`echo "$P" | cut -d'|' -f3`
				ORG=`echo "$P" | cut -d'|' -f4`
				[ ! "$NAME" ] && continue
				TIME=`printf "%02d:%02d:%02d" $((SEC/3600)) $((SEC%3600/60)) $((SEC%60))`
				echo "$GENERATOR_NR|$TIME|$NAME|$ORG|$CLASS||$SEC" >> $WORKDIR/startlist_generated
				GENERATOR_NR=$(($GENERATOR_NR+1))
				SEC=$(($SEC+$START_INTERVAL))
			done < $WORKDIR/tmp2
		done < $WORKDIR/classes
		tac $WORKDIR/startlist_generated > $WORKDIR/startlist
	fi
}

generate_edit(){
	[ ! "$CLASS_STARTTIME" ] && exit
	#read info from list
	GEN_CLASS=`grep "^$CLASS_STARTTIME|" $WORKDIR/class_starttime | cut -d'|' -f1`
	GEN_NR=`grep "^$CLASS_STARTTIME|" $WORKDIR/class_starttime | cut -d'|' -f2`
	GEN_TIME=`grep "^$CLASS_STARTTIME|" $WORKDIR/class_starttime | cut -d'|' -f3`
	#geometry
	XWININFO=`xwininfo -stats -name $LOC600`
	WIDTH=`echo "$XWININFO" | grep 'Width:' | awk '{print $2}'`
	export X=`echo "$XWININFO" | grep 'Absolute upper-left X' | awk '{print $4}'` #export to use in <progressbar> loop
	export Y=$(((`getcurpos | awk '{print $2}'`)-20))
	#---
	export gen_edit='
	<window height-request="50" width-request="'$WIDTH'" skip-taskbar-hint="true" decorated="false">
	 <vbox>
	  <hbox width-request="1">
	   <progressbar width-request="1" height-request="1" >
	    <input>LOOP2=true; while [ $LOOP2 = true ]; do MOUSEX=`getcurpos | awk '"'"'{print $1}'"'"'`; MOUSEY=`getcurpos | awk '"'"'{print $2}'"'"'`; if [ $MOUSEX -lt $X ] || [ $MOUSEX -gt '$(($X+$WIDTH))' ] || [ $MOUSEY -lt $Y ] || [ $MOUSEY -gt '$(($Y+50))' ]; then LOOP2=false; echo; echo 100; fi; sleep 1; done</input>
	    <action>EXIT:exit</action>
	   </progressbar>
	  </hbox>
	  <hbox>
	   <entry width-request="180"><input>echo '$GEN_CLASS'</input><visible>disabled</visible></entry>
	   <entry name="edit" width-request="120" activates-default="true" tooltip-text="'$LOC310'"><input>echo "'$GEN_TIME'"</input><variable>GEN_TIME</variable></entry>
	   <text width-request="'$(($WIDTH-300))'"><label>""</label></text>
	   <button visible="false" can-default="true" has-default="true"><action>EXIT:apply</action></button>
	  </hbox>
	 </vbox>
	 <action signal="focus-out-event">EXIT:exit</action>
	</window>'
	gtkdialog4 -p gen_edit -G +"$X"+"$Y" > $WORKDIR/returnvalues
	chmod 722 $WORKDIR/returnvalues
	. $WORKDIR/returnvalues
	case $EXIT in
		apply)
			HOUR=`echo $GEN_TIME | cut -d: -f1`
			MIN=`echo $GEN_TIME | cut -d: -f2`
			SEC=`echo $GEN_TIME | cut -d: -f3`
			GEN_SEC=`echo "($HOUR*3600)+($MIN*60)+$SEC" | bc`
			grep -B 10000 "^$CLASS_STARTTIME" $WORKDIR/class_starttime | grep -v "^$CLASS_STARTTIME" > $WORKDIR/tmp
			grep -A 10000 "^$CLASS_STARTTIME" $WORKDIR/class_starttime | grep -v "^$CLASS_STARTTIME" > $WORKDIR/tmp1
			echo "$GEN_CLASS|$GEN_NR|$GEN_TIME||$GEN_SEC" >> $WORKDIR/tmp
			cat $WORKDIR/tmp1 >> $WORKDIR/tmp
			mv -f $WORKDIR/tmp $WORKDIR/class_starttime
			;;
	esac
}

export -f save open edit generate generate_edit
	
export Competitors='
<window title="'$LOC112'" icon-name="gtk-no" window_position="2" height-request="500" width-request="570">
 <vbox>
  <menubar>
   <menu>
    <menuitem stock="gtk-new" label="'$LOC500'">
     <action>echo -n > '$WORKDIR'/startlist</action>
     <action>refresh:STARTLIST</action>
    </menuitem>
    <menuitem stock="gtk-open" label="'$LOC501'">
     <action>open</action>
     <action>refresh:STARTLIST</action>
    </menuitem>
    <menuitem stock="gtk-save" label="'$LOC502'">
     <action>tac '$WORKDIR'/startlist | sed '"'"'s/|/","/g'"'"' | sed "s/^/\"/g" | sed "s/$/\"/g" > '$WORKDIR'/pTiming.csv</action>
     <action>save</action>
    </menuitem>
    <separator></separator>
    <menuitem stock="gtk-edit" label="'$LOC503'">
     <action>cp '$WORKDIR'/startlist '$WORKDIR'/tmp; echo -e "\n'$LOC122'|'$LOC129'|'$LOC123'|'$LOC124'|'$LOC125'\n" >> '$WORKDIR'/tmp; tac '$WORKDIR'/tmp | cut -d"|" -f1-5 | sed '"'"'s/|/","/g'"'"' | sed "s/^/\"/g" | sed "s/$/\"/g" > '$WORKDIR'/pTiming.csv</action>
     <action>defaultspreadsheet '$WORKDIR'/pTiming.csv &</action>
    </menuitem>
    <separator></separator>
    <menuitem stock="gtk-quit" label="'$LOC_CLOSE'"><action>exit:EXIT</action></menuitem>
     <label>'$LOC100'</label>
    </menu>
    <menu>
     <menuitem stock="gtk-execute" label="'$LOC510'"><action>generate</action><action>refresh:STARTLIST</action></menuitem>
     <separator></separator>
     <menuitem><label>'$LOC121' '$LOC122'</label>
      <action>sort -nr --output='$WORKDIR'/tmp '$WORKDIR'/startlist; mv -f '$WORKDIR'/tmp '$WORKDIR'/startlist</action>
      <action>refresh:STARTLIST</action>
     </menuitem>
     <menuitem><label>'$LOC121' '$LOC129'</label>
      <action>cat '$WORKDIR'/startlist | sort -nrt "|" -k1,1 | sort -rt "|" -k2,2 --output='$WORKDIR'/tmp; mv -f '$WORKDIR'/tmp '$WORKDIR'/startlist</action>
      <action>refresh:STARTLIST</action>
     </menuitem>
     <menuitem><label>'$LOC121' '$LOC123'</label>
      <action>sort -rt "|" -k3,3 --output='$WORKDIR'/tmp '$WORKDIR'/startlist; mv -f '$WORKDIR'/tmp '$WORKDIR'/startlist</action>
      <action>refresh:STARTLIST</action></menuitem>
     <menuitem><label>'$LOC121' '$LOC124'</label>
      <action>sort -rt "|" -k4,5 --output='$WORKDIR'/tmp '$WORKDIR'/startlist; mv -f '$WORKDIR'/tmp '$WORKDIR'/startlist</action>
      <action>refresh:STARTLIST</action>
     </menuitem>
     <menuitem><label>'$LOC121' '$LOC125'</label>
      <action>sort -rt "|" -k5,6 --output='$WORKDIR'/tmp '$WORKDIR'/startlist; mv -f '$WORKDIR'/tmp '$WORKDIR'/startlist</action>
      <action>refresh:STARTLIST</action>
     </menuitem>
     <label>'$LOC120'</label>
    </menu>
   </menubar>
   <vbox>
   <frame '$LOC511'>
    <hbox>
     <text><label>'$LOC512'</label></text>
     <hbox><entry width-request="40"><variable>INCREASE</variable><default>'$START_INTERVAL'</default></entry></hbox>
    </hbox>
	<hbox>
	 <entry width-request="35" activates-default="true"><variable>ADD_NR</variable><input>echo $((ADD_NR+1))</input></entry>
	 <entry width-request="70" activates-default="true"><variable>ADD_STARTTIME</variable><default>00:02:00</default><input>HOUR=`echo $ADD_STARTTIME | cut -d: -f1`; MIN=`echo $ADD_STARTTIME | cut -d: -f2`; SEC=`echo $ADD_STARTTIME | cut -d: -f3`; TMP=$(((`echo "($HOUR*3600)+($MIN*60)+$SEC" | bc`)+$INCREASE)); printf "%02d:%02d:%02d" $(($TMP/3600)) $(($TMP%3600/60)) $(($TMP%60))</input></entry>
	 <entry width-request="135" activates-default="true"><variable>ADD_NAME</variable><default>Name</default></entry>
	 <entry width-request="130" activates-default="true"><variable>ADD_ORG</variable><default>Organization</default></entry>
	 <entry width-request="80" activates-default="true"><variable>ADD_CLASS</variable><default>Class</default></entry>
	 <button can-default="true" has-default="true">
	  <input file stock="gtk-add"></input>
	  <action>if [ ! "`grep "^$ADD_NR" '$WORKDIR'/startlist`" ]; then HOUR=`echo $ADD_STARTTIME | cut -d: -f1`; MIN=`echo $ADD_STARTTIME | cut -d: -f2`; SEC=`echo $ADD_STARTTIME | cut -d: -f3`; ADD_SEC=`echo "($HOUR*3600)+($MIN*60)+$SEC" | bc`; echo "$ADD_NR|$ADD_STARTTIME|$ADD_NAME|$ADD_ORG|$ADD_CLASS||$ADD_SEC" >> '$WORKDIR'/startlist; else TXT1="ID _${ADD_NR}_ already exist"; . '$APPDIR'/box_ok; fi</action>
	  <action>refresh:STARTLIST</action>
	  <action>refresh:ADD_NR</action>
	  <action>refresh:ADD_STARTTIME</action>
	 </button>
	</hbox>
   </frame>
   </vbox>
   <tree hover_selection="true" headers-clickable="false">
    <variable>STARTLIST</variable>
    <label>'$LOC122'|'$LOC129'|'$LOC123'                    |'$LOC124'       |'$LOC125'           |                                                  |</label> 
    <input>tac '$WORKDIR'/startlist</input>
    <action signal="button-press-event">edit</action>
    <action signal="button-press-event">refresh:STARTLIST</action>
   </tree>
   <vbox>
    <hbox>
     <button>
      <input file stock="gtk-execute"></input>
      <label>'$LOC510'</label>
      <action>generate</action>
      <action>refresh:STARTLIST</action>
     </button>
     <button ok></button>
    </hbox>
  </vbox>
 </vbox>
</window>'

gtkdialog4 -p Competitors
