#!/bin/bash

. $APPDIR/gui_menu
. $APPDIR/gui_misc
. $APPDIR/gui_add
. $APPDIR/gui_toolbar
. $APPDIR/gui_playlist
. $APPDIR/gui_navigation
. $APPDIR/gui_mixer

##reset options in case user choose another frontend from View-menu
#. $CONFIG
#export UPDATE_INTERVAL=''


GUI='
 <vbox>
  '$GUI_MENUS'

   <hbox scrollable="true" height="200" width-request="10"> ##width-request to avoid scrollbars
    <vbox space-expand="true" space-fill="true">
     <vbox space-expand="false" space-fill="false">
      <text height-request="2"><label>""</label></text>
      '$GUI_ADD_SEARCH'
     </vbox>
     <hbox space-expand="true" space-fill="true">
      '$GUI_ADD_FIELD'
     </hbox>
    </vbox>
    <vbox width-request="350">
    '$GUI_PLAYLIST_FIELD'
    </vbox>
   </hbox>

    <hbox>
     <hbox space-expand="false" space-fill="false">
      <text width-request="3"><label>""</label></text>
      '$GUI_MIXER'
     </hbox>
     <hbox space-expand="true" space-fill="true">
      <text><label>""</label></text>
     </hbox>
     '$GUI_BUTTON_SONG_INFO'
     '$GUI_BUTTON_NEW'
     '$GUI_BUTTON_PLAYLIST_HISTORY_BACK'
     '$GUI_BUTTON_PLAYLIST_HISTORY_FORWARD'
     '$GUI_NAVIGATION'
     '$GUI_BUTTON_PLAYMODE'
     '$GUI_BUTTON_ADDMODE'
   </hbox>
   '$GUI_PROGRESS'
   '$GUI_STATUSBAR'

 </vbox>
 <action signal="show">'$APPDIR'/func_mixer -get_levels</action>
 <action signal="show">refresh:VOLUME</action>
 <action signal="show">refresh:BALANCE</action>
 <action signal="show">echo > '$WORKDIR'/gui_is_running</action>
 <action signal="delete-event">rm -f '$WORKDIR'/gui_is_running</action>
 <action signal="delete-event">'$APPDIR'/func_config -write_config</action>
 <action signal="delete-event">'$APPDIR'/func -quit</action>
 <action signal="delete-event">exit:Exit</action>
</window>'
