#!/bin/bash

if [ -z "$FRAME" ]; then FRAME="Info"; fi
export ok_box="
<window title=\"Pschedule\" icon-name=\"gtk-refresh\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <text use-markup=\"true\"><label>\"$TXT2\"</label></text>
   <text use-markup=\"true\"><label>\"$TXT3\"</label></text>
  </frame>
  <hbox>
   <button>
    <input file icon=\"gtk-apply\"></input>
    <label>Ok</label>
   </button>
  </hbox>
 </vbox>
</window>"
gtkdialog3 -p ok_box --center
TXT1=""; TXT2=""; TXT3=""; IMG=""; FRAME="" #reset to avoid alien text in next box
