#!/bin/sh
MACHINE=$1
IP=$2
SHARE=$3
MOUNTPOINT=$4
USERNAME=$5
PASSWORD=$6
USECIFS=$7
IOCHARSET=$8
DOMAINID=$9
echo "func mount called: with
MACHINE=$1
IP=$2
SHARE=$3
MOUNTPOINT=$4
USERNAME=$5
PASSWORD=?
USECIFS=$7
IOCHARSET=$8
DOMAINID=$9" >> ${TMP}log
#escape dollars, spaces are substituted with \040
MOUNTED="$(mount | grep $(echo "$MOUNTPOINT" | sed 's/\$/\\$/g;s/ /\\\\040/g'))$(mount | grep "$MOUNTPOINT")"
if [ "$MOUNTED" ]; then
echo "Mount: $MACHINE $SHARE is already connected" >> ${TMP}log
else
mkdir -p "$MOUNTPOINT"

#use UTF-8 iocharset
USEIOCHARSET=""
[ "$IOCHARSET" = "true" ] && USEIOCHARSET=",iocharset=utf8"

#shinobar's blank username and password fix
USER_PASS="username=guest,guest"
[ "$USERNAME" != "" ] && USER_PASS="username=${USERNAME},password=${PASSWORD}"

#Check correct mount command
MOUNT="mount"
which mount-FULL && MOUNT="mount-FULL"

#check to see if cifs is enabled
if [ "$USECIFS" = "true" -a "$(lsmod | grep cifs)" ]; then
#check to see whether the machine name is really a name or just an ip
[ "$(echo $MACHINE | grep '^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$')" ] || SERVERNETBIOSNAME="servernetbiosname=${MACHINE},"
 if [ ! "$DOMAINID" = "" ]; then
 $MOUNT -t cifs "//${IP}/${SHARE}" "${MOUNTPOINT}" -o "${SERVERNETBIOSNAME}$USER_PASS,noserverino,workgroup=${DOMAINID}$USEIOCHARSET" 2>>${TMP}log 
 else
 $MOUNT -t cifs "//${IP}/${SHARE}" "${MOUNTPOINT}" -o "${SERVERNETBIOSNAME}$USER_PASS,noserverino$USEIOCHARSET" 2>>${TMP}log 
   if [ $? != "0" -a "$USERNAME" = "" ]; then #if mount fails with guest, try default "guest" password
   USER_PASS="username=guest,password=guest"
   $MOUNT -t cifs "//${IP}/${SHARE}" "${MOUNTPOINT}" -o "${SERVERNETBIOSNAME}$USER_PASS,noserverino$USEIOCHARSET" 2>>${TMP}log 
 fi
fi
else # default to mounting with smbmount if no cifs
if [ "$USECIFS" = "true" ]; then
export MAIN_DIALOG="<window title=\"Pnethood Error\" icon-name=\"gtk-network\"><vbox><text wrap=\"true\"><label>Unable to connect to share using Common Internet Filesystem (CIFS). You probably don't have the cifs module installed. Share will be mounted using the smb protocol. Untick the box on the main window to avoid seeing this message again.</label></text><hbox homogeneous=\"true\"><pixmap icon_size=\"5\"><input file stock=\"gtk-dialog-error\"></input></pixmap><button ok></button></hbox></vbox></window>"
gtkdialog4 --program=MAIN_DIALOG --center
fi
smbmount "//${IP}/${SHARE}" "${MOUNTPOINT}" -o "$USER_PASS,workgroup=${DOMAINID}" 2>>${TMP}log >>/dev/null # redirecting stdout needed to lose init_iconv encoding conversion error messages
fi

MOUNTED="$(mount | grep $(echo "$MOUNTPOINT" | sed 's/\$/\\$/g;s/ /\\\\040/g'))$(mount | grep "$MOUNTPOINT")"
if [ "$MOUNTED" ];then
echo Mount: "$MACHINE" "$SHARE" succeeded >> ${TMP}log
else
rmdir "$MOUNTPOINT" #I think this is safe, it will only rm if empty, this prevents use of empty mountpoint
echo Mount: "$MACHINE" "$SHARE" failed >> ${TMP}log
export MAIN_DIALOG="<window title=\"Pnethood Error\" icon-name=\"gtk-network\"><vbox><text wrap=\"true\"><label>Mount: $MACHINE $SHARE failed. The server may be refusing you access to this share or your password may be incorrect. Please hit the $SHARE disconnect button to reset the display.</label></text><hbox homogeneous=\"true\"><pixmap icon_size=\"5\"><input file stock=\"gtk-dialog-error\"></input></pixmap><button ok></button></hbox></vbox></window>"
gtkdialog4 --program=MAIN_DIALOG --center
fi
fi
