#! /bin/bash

export pbackup_splash='
<window title="Pbackup" icon-name="gtk-refresh">
<vbox>
 <frame>
  <pixmap icon_size="6"><input file stock="gtk-refresh"></input></pixmap>
  <text use-markup="true"><label>"<b>Pbackup</b>"</label></text>
  <text><input file>'"$WORKDIR"'/pbackup-splashtext</input></text>
  <progressbar>
   <label>Sigmund Berglund,   GPL 2006-2009</label>
   <input>while [ "$I" != "100" ]; do I=`cat '"$WORKDIR"'/pbackup-splash`; echo $I; usleep 500000; done</input>
   <action type="exit">" "</action>
  </progressbar>
 </frame>
</vbox></window>
'
gtkdialog3 --program=pbackup_splash --center
