#!/bin/bash

if [ -z "$FRAME" ]; then FRAME="Info"; fi
export ok_box="
<window title=\"Pbackup\" icon-name=\"gtk-refresh\">
 <vbox>
  <frame $FRAME>
   <pixmap icon_size=\"6\"><input file stock=\"gtk-$IMG\"></input></pixmap>
   <text use-markup=\"true\"><label>\"$TXT1\"</label></text>
   <text use-markup=\"true\"><label>\"$TXT2\"</label></text>
   <text $ATTR use-markup=\"true\"><label>\"$TXT3\"</label></text>
  </frame>
  <hbox>
   <button can-default=\"true\" has-default=\"true\" use-stock=\"true\">
    <input file icon=\"gtk-apply\"></input>
    <label>$LOC_OK</label>
   </button>
  </hbox>
 </vbox>
</window>"
gtkdialog3 --program=ok_box --center
TXT1=""; TXT2=""; TXT3=""; IMG=""; FRAME=""; ATTR="" #reset to avoid alien text in next box
