#!/bin/bash

RESULT=`Xdialog --stdout --title "Pbackup" --screen-center --cancel-label "$LOC_CANCEL" --ok-label "$LOC_OK" --calendar "$LOC505" 350x270 $BCKDATE_FROM3`
if [ $? = 0 ]; then
	echo $RESULT > $WORKDIR/pbackup-BCKDATE_FROM
fi
